name: nasa_daily_app
description: "A Flutter project for show and favorite image from Nasa API"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  flutter_modular: ^5.0.3
  get_it: ^7.2.0
  intl: 0.19.0
  sizer: ^2.0.13
  flutter_svg: ^2.0.5
  flutter_animate: ^4.1.0
  dio: ^5.2.1+1
  shared_preferences: ^2.3.0
  cached_network_image: ^3.4.1
  easy_image_viewer: ^1.5.1
  video_player: ^2.9.3
  flutter_widget_from_html: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  analyzer: ^6.4.1
  mobx_codegen: ^2.0.7
  mocktail: ^1.0.3
  modular_test: ^2.0.0
  faker: ^2.1.0
  build_runner: ^2.3.3
  google_fonts: ^4.0.3

flutter:
  uses-material-design: true
  assets:
    - lib/core/design/assets/icons/
    - lib/core/design/assets/images/
flutter_intl:
  enabled: true
  main_locale: pt_BR